version: '3.4'

services:
  api:
    build:
      context: .
      target: development
    environment:
      APP_SECRET: ${APP_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      APP_WEB_URL: ${APP_WEB_URL}
      PORT: ${PORT}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_SRC_BASE: ${DB_SRC_BASE}
      DB_ENV: ${DB_ENV}
      DB_PORT: ${DB_PORT}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-connect
    depends_on:
      - mongo-app
    command: >
      sh -c "yarn dev"

  mongo-app:
    container_name: ${DB_HOST}
    image: mongo
    restart: always
    volumes:
      - romeu-data:/data
    environment:
      MONGO_DB: ${DB_NAME}
      MONGO_USER: ${DB_USER}
      MONGO_PASSWORD: ${DB_PASS}
    networks:
      - app-connect
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  romeu-data:

networks:
  app-connect:
    driver: bridge
